"""
Zero-shot 26-class haplogroup k-NN evaluation for the mtDNA-FM paper.

Pipeline
--------
1. Use haplogroup-labeled NCBI sequences from data/hmtdb_labeled/
   (generated by paper/download_labeled_mtdna.py)
2. Preprocess sequences: clean + normalise to 16,569 bp
3. Map sub-haplogroup labels → 26 major PhyloTree classes
4. Stratified 80/10/10 split (random_state=42, same as training)
5. Sample balanced evaluation set:
      - Test queries : up to TEST_PER_CLASS per class
      - Train library: up to TRAIN_PER_CLASS per class
6. Load mtDNA-FM from HuggingFace Hub (batched window inference for speed)
7. k-NN classification  (k=5, cosine distance)
8. Accuracy, macro-F1, per-class metrics, 1 000-replicate bootstrap 95% CI
9. Save → reports/zeroshot_haplogroup_knn.json

Prerequisites
-------------
    uv run python paper/download_labeled_mtdna.py   # run first

Usage
-----
    uv run python paper/run_zeroshot_haplogroup.py

Expected runtime (Intel Core i7, CPU-only, ~1300 sequences total)
-----------------------------------------------------------------
  Embedding  ~1 300 sequences (batched windows): ≈ 20–60 minutes
  k-NN + bootstrap                              : < 1 minute
"""

from __future__ import annotations

import json
import logging
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ── Configuration ──────────────────────────────────────────────────────────────
DATA_DIR_LABELED = ROOT / "data" / "hmtdb_labeled"
REPORTS_DIR      = ROOT / "reports"
OUTPUT_JSON      = REPORTS_DIR / "zeroshot_haplogroup_knn.json"
MODEL_REPO       = "vthawfeek/mtdna-foundation-model"

TEST_PER_CLASS   = 40    # max test-query sequences per class
TRAIN_PER_CLASS  = 60    # max train-library sequences per class
KNN_K            = 5
BOOTSTRAP_N      = 1_000
RANDOM_STATE     = 42

MAJOR_26 = {
    "A", "B", "C", "D", "E", "F", "G", "H", "HV", "I", "J", "K",
    "L0", "L1", "L2", "L3", "L4", "L5", "M", "N", "R", "T", "U", "V", "W", "X",
}


# ── Haplogroup mapping ─────────────────────────────────────────────────────────

def map_haplogroup(raw: object) -> str | None:
    """Map a raw haplogroup string to one of the 26 major classes."""
    if raw is None:
        return None
    s = str(raw).strip()
    if not s or s.lower() in ("nan", "none", "", "?", "-"):
        return None
    upper = s.upper()
    # HV must come before H (HV1, HV2... → "HV")
    if upper.startswith("HV"):
        return "HV"
    # L sub-clades: L0–L5 (L0a1, L3e2b → L0, L3)
    if upper.startswith("L") and len(s) > 1 and s[1].isdigit():
        major = upper[:2]
        return major if major in MAJOR_26 else None
    # All others: first character
    major = upper[0]
    return major if major in MAJOR_26 else None


# ── Step 1: Load data ──────────────────────────────────────────────────────────

def load_data() -> "pd.DataFrame":
    import pandas as pd
    from Bio import SeqIO
    from mtdna_fm.data.preprocessor import clean_sequence, normalize_length

    fasta_path = DATA_DIR_LABELED / "sequences.fasta"
    meta_path  = DATA_DIR_LABELED / "metadata.parquet"

    if not fasta_path.exists() or not meta_path.exists():
        log.error(
            "Data not found at %s. Run paper/download_labeled_mtdna.py first.",
            DATA_DIR_LABELED,
        )
        sys.exit(1)

    log.info("Loading metadata …")
    meta_df = pd.read_parquet(meta_path)
    log.info("  %d metadata rows, columns: %s", len(meta_df), list(meta_df.columns))

    # Build sequence DataFrame from FASTA
    log.info("Parsing FASTA …")
    rows = []
    for rec in SeqIO.parse(fasta_path, "fasta"):
        rows.append({"accession": rec.id, "sequence": str(rec.seq)})
    seq_df = pd.DataFrame(rows)
    log.info("  %d sequences in FASTA", len(seq_df))

    # Merge
    df = seq_df.merge(
        meta_df[["accession", "haplogroup"]],
        on="accession", how="left",
    )

    # Map to major haplogroup
    df["major_hg"] = df["haplogroup"].apply(map_haplogroup)

    labeled = df[df["major_hg"].notna()].copy()
    log.info("  %d sequences with a valid major haplogroup label", len(labeled))

    import collections
    dist = collections.Counter(labeled["major_hg"].tolist())
    log.info("  Classes found: %d  |  top 10: %s",
             len(dist), sorted(dist.items(), key=lambda x: -x[1])[:10])

    # Preprocess sequences
    log.info("Preprocessing sequences (clean + normalize to 16,569 bp) …")
    labeled = labeled.copy()
    labeled["sequence"] = labeled["sequence"].apply(clean_sequence)
    labeled["sequence"] = labeled["sequence"].apply(normalize_length)

    # QC: drop sequences with > 10% N
    n_frac = labeled["sequence"].apply(lambda s: s.count("N") / len(s))
    labeled = labeled[n_frac <= 0.10].copy()
    log.info("  After QC: %d sequences", len(labeled))

    return labeled


# ── Step 2: Split ──────────────────────────────────────────────────────────────

def prepare_splits(df: "pd.DataFrame") -> tuple["pd.DataFrame", "pd.DataFrame"]:
    from mtdna_fm.data.preprocessor import stratified_split

    log.info("Stratified 80/10/10 split (random_state=%d) …", RANDOM_STATE)
    df = stratified_split(df, label_col="major_hg", random_state=RANDOM_STATE)

    train_df = df[df["split"] == "train"].copy()
    test_df  = df[df["split"] == "test"].copy()

    # Only keep classes present in both splits
    common = sorted(set(train_df["major_hg"]) & set(test_df["major_hg"]))
    log.info("  Train: %d   Test: %d   Shared classes: %d",
             len(train_df), len(test_df), len(common))

    train_df = train_df[train_df["major_hg"].isin(common)]
    test_df  = test_df[test_df["major_hg"].isin(common)]
    return train_df, test_df


def sample_balanced(df: "pd.DataFrame", n_per_class: int, seed: int,
                    label_col: str = "major_hg") -> "pd.DataFrame":
    import pandas as pd
    frames = []
    for _, group in df.groupby(label_col):
        n = min(n_per_class, len(group))
        frames.append(group.sample(n, random_state=seed))
    out = pd.concat(frames, ignore_index=True).sample(frac=1, random_state=seed)
    log.info("  Balanced sample: %d seqs across %d classes",
             len(out), out[label_col].nunique())
    return out


# ── Step 3: Load model ─────────────────────────────────────────────────────────

def load_embedder():
    log.info("Loading model from HuggingFace Hub (%s) …", MODEL_REPO)
    from mtdna_fm.model.model import MtDNAForMaskedModeling
    from mtdna_fm.tokenizer.vocabulary import KmerVocabulary
    from mtdna_fm.inference.api import MtDNAEmbedder

    vocabulary = KmerVocabulary.from_pretrained(MODEL_REPO)
    full_model = MtDNAForMaskedModeling.from_pretrained(MODEL_REPO)
    encoder    = full_model.mtdna
    embedder   = MtDNAEmbedder(encoder, vocabulary, device="cpu")
    n_params   = sum(p.numel() for p in encoder.parameters())
    log.info("  Loaded. Parameters: %.2f M", n_params / 1e6)
    return embedder


# ── Step 4: Batched genome embedding ──────────────────────────────────────────

def embed_genome_batched(embedder, sequence: str) -> np.ndarray:
    """
    Embed a full genome by batching ALL sliding windows in one forward pass.

    ~5–10× faster than the sequential MtDNAEmbedder.embed_genome because it
    avoids per-window Python overhead. Result is identical (mean of CLS tokens).
    """
    import torch
    from mtdna_fm.tokenizer.tokenize import tokenize_sequence

    k = embedder.k
    window_size = embedder.window_size
    stride = embedder.stride
    device = embedder.device

    genome_length = embedder.model.config.genome_length
    if len(sequence) > genome_length:
        sequence = sequence[:genome_length]
    elif len(sequence) < genome_length:
        sequence = sequence + "N" * (genome_length - len(sequence))

    tokens = tokenize_sequence(
        sequence, embedder.vocabulary, k=k, stride=1,
        max_seq_len=len(sequence), circular=True, het_levels=None,
    )
    n_tokens = len(tokens["input_ids"])

    all_input_ids    = []
    all_position_ids = []
    all_het_values   = []

    for start in range(0, n_tokens, stride):
        idx = [(start + i) % n_tokens for i in range(window_size)]
        all_input_ids.append([tokens["input_ids"][j]    for j in idx])
        all_position_ids.append([tokens["position_ids"][j] for j in idx])
        all_het_values.append([tokens["het_values"][j]  for j in idx])

    batch_input_ids    = torch.tensor(all_input_ids,    dtype=torch.long).to(device)
    batch_position_ids = torch.tensor(all_position_ids, dtype=torch.long).to(device)
    batch_het_values   = torch.tensor(all_het_values,   dtype=torch.float).to(device)

    with torch.no_grad():
        out = embedder.model(
            input_ids=batch_input_ids,
            position_ids=batch_position_ids,
            het_values=batch_het_values,
        )

    cls_vectors = out.pooler_output.cpu().numpy()   # (n_windows, hidden_size)
    return cls_vectors.mean(axis=0)


def embed_sequences(embedder, df: "pd.DataFrame", desc: str = "") -> np.ndarray:
    sequences = df["sequence"].tolist()
    n = len(sequences)
    embeddings = []
    t0 = time.time()

    for i, seq in enumerate(sequences):
        embeddings.append(embed_genome_batched(embedder, seq))

        if (i + 1) % 20 == 0 or (i + 1) == n:
            elapsed = time.time() - t0
            rate = (i + 1) / elapsed
            eta  = (n - i - 1) / rate if rate > 0 else 0
            log.info("  %s  %d/%d  (%.1f seq/min, ETA %.0f min)",
                     desc, i + 1, n, rate * 60, eta / 60)

    return np.stack(embeddings, axis=0).astype(np.float32)


# ── Step 5: k-NN classification ────────────────────────────────────────────────

def cosine_knn_predict(
    train_emb: np.ndarray, train_labels: np.ndarray,
    test_emb: np.ndarray, k: int = 5,
) -> np.ndarray:
    train_norm = train_emb / (np.linalg.norm(train_emb, axis=1, keepdims=True) + 1e-12)
    test_norm  = test_emb  / (np.linalg.norm(test_emb,  axis=1, keepdims=True) + 1e-12)
    sim = test_norm @ train_norm.T   # (n_test, n_train)

    unique_labels = sorted(set(train_labels.tolist()))
    label_to_idx  = {l: i for i, l in enumerate(unique_labels)}
    train_idx     = np.array([label_to_idx[l] for l in train_labels])

    predictions = []
    for i in range(len(test_emb)):
        top_k  = np.argsort(-sim[i])[:k]
        votes  = np.bincount(train_idx[top_k], minlength=len(unique_labels))
        predictions.append(unique_labels[int(np.argmax(votes))])

    return np.array(predictions)


def compute_metrics(y_true: np.ndarray, y_pred: np.ndarray,
                    classes: list[str]) -> dict:
    from sklearn.metrics import accuracy_score, f1_score, precision_recall_fscore_support

    acc      = float(accuracy_score(y_true, y_pred))
    macro_f1 = float(f1_score(y_true, y_pred, average="macro",
                              zero_division=0, labels=classes))
    p, r, f, sup = precision_recall_fscore_support(
        y_true, y_pred, labels=classes, zero_division=0)

    per_class = [
        {"label": cls, "precision": round(float(p[i]), 4),
         "recall": round(float(r[i]), 4), "f1": round(float(f[i]), 4),
         "support": int(sup[i])}
        for i, cls in enumerate(classes)
    ]
    return {"accuracy": round(acc, 4), "macro_f1": round(macro_f1, 4),
            "per_class": per_class}


def bootstrap_accuracy(y_true: np.ndarray, y_pred: np.ndarray,
                        n: int = BOOTSTRAP_N, seed: int = RANDOM_STATE
                        ) -> tuple[float, float]:
    rng     = np.random.default_rng(seed)
    correct = (y_true == y_pred).astype(float)
    boot    = [correct[rng.integers(0, len(correct), size=len(correct))].mean()
               for _ in range(n)]
    lo, hi  = np.percentile(boot, [2.5, 97.5])
    return round(float(lo), 4), round(float(hi), 4)


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    # 1. Load
    df = load_data()

    # 2. Split
    train_df, test_df = prepare_splits(df)
    classes = sorted(set(train_df["major_hg"]) & set(test_df["major_hg"]))
    n_classes = len(classes)
    random_baseline = round(1.0 / n_classes, 4)
    log.info("Classes: %d   Random baseline: %.1f%%", n_classes, random_baseline * 100)

    train_lib = sample_balanced(train_df, TRAIN_PER_CLASS, RANDOM_STATE)
    test_q    = sample_balanced(test_df,  TEST_PER_CLASS,  RANDOM_STATE + 1)
    log.info("Train library: %d   Test queries: %d", len(train_lib), len(test_q))

    # 3. Load model
    embedder = load_embedder()

    # 4. Embed
    log.info("Embedding train library (%d sequences) …", len(train_lib))
    t0 = time.time()
    train_emb = embed_sequences(embedder, train_lib, desc="train")
    log.info("  Train embedding done in %.1f min", (time.time() - t0) / 60)

    log.info("Embedding test queries (%d sequences) …", len(test_q))
    t0 = time.time()
    test_emb = embed_sequences(embedder, test_q, desc="test ")
    log.info("  Test embedding done in %.1f min", (time.time() - t0) / 60)

    # 5. k-NN
    log.info("Running %d-NN (cosine) …", KNN_K)
    train_labels = train_lib["major_hg"].to_numpy()
    test_labels  = test_q["major_hg"].to_numpy()
    y_pred = cosine_knn_predict(train_emb, train_labels, test_emb, k=KNN_K)

    # 6. Metrics
    metrics = compute_metrics(test_labels, y_pred, classes=classes)
    ci_lo, ci_hi = bootstrap_accuracy(test_labels, y_pred)
    lift = round(metrics["accuracy"] / random_baseline, 2) if random_baseline > 0 else None

    log.info("=" * 60)
    log.info("RESULTS — %d-class zero-shot %d-NN", n_classes, KNN_K)
    log.info("  Accuracy  : %.1f%%  (95%% CI %.1f%%–%.1f%%)",
             metrics["accuracy"] * 100, ci_lo * 100, ci_hi * 100)
    log.info("  Random    : %.1f%%  (1/%d)", random_baseline * 100, n_classes)
    log.info("  Lift      : %.1f×", lift)
    log.info("  Macro-F1  : %.4f", metrics["macro_f1"])
    log.info("=" * 60)

    # 7. Save
    result = {
        "method":             f"zero-shot cosine {KNN_K}-NN",
        "model":              MODEL_REPO,
        "n_classes":          n_classes,
        "classes":            classes,
        "n_train_library":    int(len(train_lib)),
        "n_test_queries":     int(len(test_q)),
        "train_per_class":    TRAIN_PER_CLASS,
        "test_per_class":     TEST_PER_CLASS,
        "random_baseline":    random_baseline,
        "accuracy":           metrics["accuracy"],
        "accuracy_ci_95_lo":  ci_lo,
        "accuracy_ci_95_hi":  ci_hi,
        "lift_over_random":   lift,
        "macro_f1":           metrics["macro_f1"],
        "per_class":          metrics["per_class"],
        "knn_k":              KNN_K,
        "random_state":       RANDOM_STATE,
        "bootstrap_n":        BOOTSTRAP_N,
    }
    with open(OUTPUT_JSON, "w") as f:
        json.dump(result, f, indent=2)
    log.info("Saved → %s", OUTPUT_JSON)


if __name__ == "__main__":
    main()
